import { Service } from "./models";
import type {
  NotificationRecord,
  ActivityRecord,
  SectionRecord,
  ActivityCalendarRecord,
  BookingRecord,
  EmailSettingsRecord,
  PaymentSettingsRecord,
  AdminRecord,
  ClientRecord,
  PartnerRecord,
  PasswordResetRecord,
  MenuItemRecord,
  AnalyticsCounterRecord,
  OrderRecord,
  ReviewRecord,
  ChatMessageRecord,
} from "./models";
import {
  activities as staticActivities,
  sections as staticSections,
} from "./data";
import type { SliderImage } from "./models";

export const mockServices: Service[] = [
  {
    id: "mock-service-1",
    name: "API Gateway",
    description: "Шлюз для микросервисной архитектуры",
    status: "active",
    url: "https://api.example.com",
    createdAt: new Date("2024-01-15").toISOString(),
    updatedAt: new Date("2024-01-15").toISOString(),
  },
  {
    id: "mock-service-2",
    name: "Auth Service",
    description: "Сервис аутентификации и авторизации",
    status: "active",
    url: "https://auth.example.com",
    createdAt: new Date("2024-02-01").toISOString(),
    updatedAt: new Date("2024-02-01").toISOString(),
  },
  {
    id: "mock-service-3",
    name: "ML Pipeline",
    description: "Пайплайн для обработки данных с AI",
    status: "deploying",
    url: undefined,
    createdAt: new Date("2024-03-10").toISOString(),
    updatedAt: new Date("2024-03-10").toISOString(),
  },
];

function mapStaticActivityToRecord(
  a: (typeof staticActivities)[number]
): ActivityRecord {
  return {
    id: a.id,
    title: a.title,
    shortDescription: a.shortDescription,
    description: a.description,
    images: a.images,
    section: a.category,
    price: a.price,
    partnerPrice: a.partnerPrice,
    likes: a.likes,
    isPopular: a.isPopular,
    over18: false,
    activityType: "individual",
    orderType: "order_form",
    imageGradient: a.imageGradient,
    location: a.location,
    status: "active" as const,
    partnerEmail: undefined,
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  };
}

export const mockActivities: ActivityRecord[] = staticActivities.map(
  mapStaticActivityToRecord
);

export const mockSections: SectionRecord[] = staticSections.map((s) => ({
  id: s.slug,
  name: s.name,
  description: s.description,
  icon: s.icon,
  imageGradient: s.imageGradient,
  category: s.category,
  createdAt: new Date("2024-06-01").toISOString(),
  updatedAt: new Date("2024-06-01").toISOString(),
}));

function generateMockDates(): Record<
  string,
  { available: boolean; hours?: string[] }
> {
  const result: Record<string, { available: boolean; hours?: string[] }> = {};
  const today = new Date();
  for (let i = 1; i <= 30; i++) {
    const d = new Date(today);
    d.setUTCDate(d.getUTCDate() + i);
    const dateStr = d.toISOString().split("T")[0];
    const available = i % 3 !== 0;
    result[dateStr] = {
      available,
      ...(available && i % 2 === 0
        ? { hours: ["10:00", "12:00", "14:00", "16:00", "18:00"] }
        : {}),
    };
  }
  return result;
}

export const mockCalendars: ActivityCalendarRecord[] = staticActivities.map(
  (a) => ({
    activityId: a.id,
    dates: generateMockDates(),
    updatedAt: new Date().toISOString(),
  })
);

export const mockBookings: BookingRecord[] = [
  {
    id: "mock-booking-1",
    clientEmail: "test@example.com",
    clientName: "Тест Пользователь",
    clientPhone: "+7 (999) 123-45-67",
    activityId: "gastronomic-tour",
    activityTitle: "Гастрономический тур",
    date: new Date(Date.now() + 86400000 * 7).toISOString().split("T")[0],
    time: "12:00",
    details: "",
    price: 3500,
    status: "confirmed",
    paymentId: null,
    paymentUrl: null,
    paymentStatus: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-booking-2",
    clientEmail: "test@example.com",
    clientName: "Тест Пользователь",
    clientPhone: "+7 (999) 123-45-67",
    activityId: "extreme-rafting",
    activityTitle: "Рафтинг по горной реке",
    date: new Date(Date.now() + 86400000 * 14).toISOString().split("T")[0],
    time: null,
    details: "Хочу увидеть пороги!",
    price: 5000,
    status: "pending_payment",
    paymentId: "mock-payment-id",
    paymentUrl: null,
    paymentStatus: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-booking-3",
    clientEmail: "test@example.com",
    clientName: "Тест Пользователь",
    clientPhone: "+7 (999) 123-45-67",
    activityId: "extreme-rafting",
    activityTitle: "Рафтинг по горной реке",
    date: new Date(Date.now() - 86400000 * 30).toISOString().split("T")[0],
    time: "14:00",
    details: "Отменили по погодным условиям",
    price: 5000,
    status: "cancelled",
    paymentId: null,
    paymentUrl: null,
    paymentStatus: null,
    createdAt: new Date(Date.now() - 86400000 * 35).toISOString(),
  },
];

export const mockEmailSettings: EmailSettingsRecord = {
  id: "default",
  emails: ["artkmv1@ya.ru"],
  defaultEmail: "artkmv1@ya.ru",
  updatedAt: new Date().toISOString(),
};

export const mockPaymentSettings: PaymentSettingsRecord = {
  id: "default",
  terminalKey: "",
  password: "",
  webhookUrl: "",
  updatedAt: new Date().toISOString(),
};

export const mockAdmins: AdminRecord[] = [
  {
    email: "artkmv1@ya.ru",
    password: "Artkmv11",
    name: "Главный администратор",
    role: "main_admin",
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
];

export const mockClients: ClientRecord[] = [
  {
    email: "ivan@example.com",
    name: "Иван Петров",
    phone: "+7 (999) 111-22-33",
    passwordHash: "hash123",
    createdAt: new Date("2024-03-01").toISOString(),
  },
  {
    email: "elena@example.com",
    name: "Елена Смирнова",
    phone: "+7 (999) 444-55-66",
    passwordHash: "hash456",
    createdAt: new Date("2024-04-15").toISOString(),
  },
  {
    email: "alexey@example.com",
    name: "Алексей Кузнецов",
    phone: "+7 (999) 777-88-99",
    passwordHash: "hash789",
    createdAt: new Date("2024-05-20").toISOString(),
  },
];

export const mockPartners: PartnerRecord[] = [
  {
    email: "partner@example.com",
    name: "Партнёр Иванов",
    phone: "+7 (999) 000-11-22",
    passwordHash: "hash:partner",
    photo: "",
    description:
      "<p>Профессиональный организатор активного отдыха в Крыму. Более 5 лет опыта проведения морских прогулок, треккинга и экскурсий.</p>",
    createdAt: new Date("2024-06-01").toISOString(),
  },
];

export const mockPartnerActivities: ActivityRecord[] = [
  {
    id: "morskoe-puteshestvie",
    title: "Морское путешествие",
    shortDescription: "Увлекательная прогулка на яхте вдоль побережья",
    description: "<p>Приглашаем вас в незабываемое морское путешествие!</p>",
    images: [],
    section: "vodnye",
    price: 5000,
    likes: 0,
    isPopular: false,
    over18: false,
    orderType: "order_form",
    activityType: "individual",
    imageGradient: "from-blue-400 to-cyan-500",
    location: "г. Севастополь",
    status: "active",
    partnerEmail: "partner@example.com",
    createdAt: new Date("2024-07-01").toISOString(),
    updatedAt: new Date("2024-07-03").toISOString(),
  },
  {
    id: "gornyj-trekking-aj-petri",
    title: "Горный треккинг на Ай-Петри",
    shortDescription: "Восхождение на одну из красивейших гор Крыма",
    description: "<p>Покорите вершину Ай-Петри!</p>",
    images: [],
    section: "trekking",
    price: 3500,
    likes: 0,
    isPopular: false,
    over18: false,
    orderType: "order_form",
    activityType: "individual",
    imageGradient: "from-emerald-400 to-cyan-500",
    location: "г. Ялта",
    status: "active",
    partnerEmail: "partner@example.com",
    createdAt: new Date("2024-07-02").toISOString(),
    updatedAt: new Date("2024-07-04").toISOString(),
  },
  {
    id: "degustacia-vin",
    title: "Дегустация крымских вин",
    shortDescription: "Знакомство с лучшими винодельнями полуострова",
    description: "<p>Откройте для себя мир крымского виноделия!</p>",
    images: [],
    section: "gastronomiya",
    price: 2500,
    likes: 2,
    isPopular: false,
    over18: true,
    orderType: "order_form",
    activityType: "individual",
    imageGradient: "from-rose-400 to-purple-500",
    location: "г. Балаклава",
    status: "pending",
    partnerEmail: "partner@example.com",
    createdAt: new Date("2024-08-01").toISOString(),
    updatedAt: new Date("2024-08-01").toISOString(),
  },
  {
    id: "kvest-po-staromu-gorodu",
    title: "Квест по старому городу",
    shortDescription: "Интерактивная прогулка с загадками и историей",
    description: "<p>Узнайте город с новой стороны!</p>",
    images: [],
    section: "razvlecheniya",
    price: 1500,
    likes: 0,
    isPopular: false,
    over18: false,
    orderType: "order_form",
    activityType: "individual",
    imageGradient: "from-amber-400 to-orange-500",
    location: "г. Симферополь",
    status: "rejected",
    partnerEmail: "partner@example.com",
    createdAt: new Date("2024-07-15").toISOString(),
    updatedAt: new Date("2024-07-20").toISOString(),
  },
];

export const mockPartnerBookings: BookingRecord[] = [
  {
    id: "mock-partner-booking-1",
    clientEmail: "ivan@example.com",
    clientName: "Иван Петров",
    clientPhone: "+7 (999) 111-22-33",
    activityId: "morskoe-puteshestvie",
    activityTitle: "Морское путешествие",
    date: new Date(Date.now() + 86400000 * 5).toISOString().split("T")[0],
    time: "10:00",
    details: "Жду с нетерпением!",
    price: 5000,
    status: "confirmed",
    paymentId: null,
    paymentUrl: null,
    paymentStatus: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-partner-booking-2",
    clientEmail: "elena@example.com",
    clientName: "Елена Смирнова",
    clientPhone: "+7 (999) 444-55-66",
    activityId: "morskoe-puteshestvie",
    activityTitle: "Морское путешествие",
    date: new Date(Date.now() + 86400000 * 12).toISOString().split("T")[0],
    time: null,
    details: "Хочу взять с собой ребёнка, возможно ли это?",
    price: 5000,
    status: "confirmed",
    paymentId: null,
    paymentUrl: null,
    paymentStatus: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-partner-booking-3",
    clientEmail: "alexey@example.com",
    clientName: "Алексей Кузнецов",
    clientPhone: "+7 (999) 777-88-99",
    activityId: "gornyj-trekking-aj-petri",
    activityTitle: "Горный треккинг на Ай-Петри",
    date: new Date(Date.now() + 86400000 * 8).toISOString().split("T")[0],
    time: "08:00",
    details: "",
    price: 3500,
    status: "pending_payment",
    paymentId: "mock-payment-3",
    paymentUrl: null,
    paymentStatus: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-partner-booking-4",
    clientEmail: "ivan@example.com",
    clientName: "Иван Петров",
    clientPhone: "+7 (999) 111-22-33",
    activityId: "gornyj-trekking-aj-petri",
    activityTitle: "Горный треккинг на Ай-Петри",
    date: new Date(Date.now() + 86400000 * 3).toISOString().split("T")[0],
    time: null,
    details: "Возьму с собой снаряжение",
    price: 3500,
    status: "confirmed",
    paymentId: null,
    paymentUrl: null,
    paymentStatus: null,
    createdAt: new Date().toISOString(),
  },
];

export const mockPendingActivities: ActivityRecord[] = [
  {
    id: "degustacia-vin",
    title: "Дегустация крымских вин",
    shortDescription: "Знакомство с лучшими винодельнями полуострова",
    description: "<p>Откройте для себя мир крымского виноделия!</p>",
    images: [],
    section: "gastronomiya",
    price: 2500,
    likes: 2,
    isPopular: false,
    over18: true,
    orderType: "order_form",
    activityType: "individual",
    imageGradient: "from-rose-400 to-purple-500",
    location: "г. Балаклава",
    status: "pending",
    partnerEmail: "partner@example.com",
    createdAt: new Date("2024-08-01").toISOString(),
    updatedAt: new Date("2024-08-01").toISOString(),
  },
];

export const mockPasswordResets: PasswordResetRecord[] = [];

export const mockMenuItems: MenuItemRecord[] = [
  {
    id: "mock-admin-dashboard",
    menuType: "admin",
    name: "Дашборд",
    url: "/admin",
    order: 1,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-admin-activities",
    menuType: "admin",
    name: "Активности",
    url: "/admin",
    order: 2,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-client-home",
    menuType: "client",
    name: "Главная",
    url: "/",
    order: 1,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-client-bookings",
    menuType: "client",
    name: "Мои бронирования",
    url: "/client/bookings",
    order: 2,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-client-notifications",
    menuType: "client",
    name: "Уведомления и чат",
    url: "/client/notifications",
    order: 3,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-partner-dashboard",
    menuType: "partner",
    name: "Дашборд",
    url: "/partner",
    order: 1,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-partner-activities",
    menuType: "partner",
    name: "Мои активности",
    url: "/partner/activities",
    order: 2,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-partner-orders",
    menuType: "partner",
    name: "Заказы",
    url: "/partner/orders",
    order: 3,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-partner-profile",
    menuType: "partner",
    name: "Профиль",
    url: "/partner/profile",
    order: 4,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-partner-public-profile",
    menuType: "partner",
    name: "Публичный профиль",
    url: "/partner/profile/public",
    order: 5,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-partner-notifications",
    menuType: "partner",
    name: "Уведомления и чат",
    url: "/partner/notifications",
    order: 6,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-footer-about",
    menuType: "footer",
    name: "О нас",
    url: "/about",
    order: 1,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-footer-contacts",
    menuType: "footer",
    name: "Контакты",
    url: "/contacts",
    order: 2,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-footer-policy",
    menuType: "footer",
    name: "Политика конфиденциальности",
    url: "/privacy",
    order: 3,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
];

export const mockAnalyticsCounters: AnalyticsCounterRecord[] = [];

export const mockNotifications: NotificationRecord[] = [
  {
    id: "mock-notif-client-1",
    recipientEmail: "test@example.com",
    type: "booking_status",
    title: "Бронирование подтверждено",
    message:
      "Ваше бронирование на «Гастрономический тур» подтверждено. Дата: 12 августа 2025.",
    link: "/client/bookings/mock-booking-1",
    isRead: false,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "mock-notif-client-2",
    recipientEmail: "test@example.com",
    type: "booking_status",
    title: "Ожидает оплаты",
    message:
      "Бронирование на «Рафтинг по горной реке» ожидает оплаты. Перейдите к оплате, чтобы завершить бронирование.",
    link: "/client/bookings/mock-booking-2",
    isRead: false,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "mock-notif-client-3",
    recipientEmail: "test@example.com",
    type: "booking_status",
    title: "Бронирование отменено",
    message:
      "Бронирование на «Рафтинг по горной реке» отменено по погодным условиям.",
    link: "/client/bookings/mock-booking-3",
    isRead: true,
    createdAt: new Date(Date.now() - 86400000 * 35).toISOString(),
  },
  {
    id: "mock-notif-partner-1",
    recipientEmail: "partner@example.com",
    type: "new_order",
    title: "Новый заказ",
    message: "Иван Петров забронировал «Морское путешествие» на 26 июля 2025.",
    link: "/partner/orders",
    isRead: false,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "mock-notif-partner-2",
    recipientEmail: "partner@example.com",
    type: "new_order",
    title: "Новый заказ",
    message:
      "Елена Смирнова забронировала «Морское путешествие» на 2 августа 2025.",
    link: "/partner/orders",
    isRead: false,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "mock-notif-partner-3",
    recipientEmail: "partner@example.com",
    type: "activity_status",
    title: "Активность отклонена",
    message: "Ваша активность «Квест по старому городу» отклонена модератором.",
    link: "/partner/activities",
    isRead: true,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "mock-notif-partner-4",
    recipientEmail: "partner@example.com",
    type: "activity_status",
    title: "Активность на проверке",
    message:
      "Ваша активность «Дегустация крымских вин» отправлена на проверку модератору.",
    link: "/partner/activities",
    isRead: false,
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
];

export const mockChatMessages: ChatMessageRecord[] = [
  {
    id: "mock-chat-1",
    orderId: "mock-order-3",
    senderEmail: "ivan@example.com",
    senderRole: "client",
    text: "Здравствуйте! Хотел уточнить, где именно происходит сбор перед морской прогулкой?",
    clientEmail: "ivan@example.com",
    partnerEmail: "partner@example.com",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "mock-chat-2",
    orderId: "mock-order-3",
    senderEmail: "partner@example.com",
    senderRole: "partner",
    text: "Здравствуйте! Сбор на причале №5 в Севастополе, бухта Артиллерийская. За 15 минут до начала.",
    clientEmail: "ivan@example.com",
    partnerEmail: "partner@example.com",
    createdAt: new Date(Date.now() - 86400000 * 2 + 3600000).toISOString(),
  },
  {
    id: "mock-chat-3",
    orderId: "mock-order-3",
    senderEmail: "ivan@example.com",
    senderRole: "client",
    text: "Спасибо! А что нужно брать с собой?",
    clientEmail: "ivan@example.com",
    partnerEmail: "partner@example.com",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "mock-chat-4",
    orderId: "mock-order-3",
    senderEmail: "partner@example.com",
    senderRole: "partner",
    text: "Возьмите головной убор, крем от загара и воду. Остальное предоставим мы.",
    clientEmail: "ivan@example.com",
    partnerEmail: "partner@example.com",
    createdAt: new Date(Date.now() - 86400000 + 1800000).toISOString(),
  },
  {
    id: "mock-chat-5",
    orderId: "mock-order-4",
    senderEmail: "elena@example.com",
    senderRole: "client",
    text: "Добрый день! Можно ли перенести прогулку на день раньше?",
    clientEmail: "elena@example.com",
    partnerEmail: "partner@example.com",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const mockReviews: ReviewRecord[] = [
  {
    id: "mock-review-1",
    activityId: "gastronomic-tour",
    clientEmail: "ivan@example.com",
    clientName: "Иван Петров",
    rating: 5,
    text: "Отличный тур! Всё очень понравилось, особенно дегустация местных вин. Обязательно вернусь ещё.",
    status: "approved",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "mock-review-2",
    activityId: "gastronomic-tour",
    clientEmail: "elena@example.com",
    clientName: "Елена Смирнова",
    rating: 4,
    text: "Хорошая организация, вкусная еда. Немного не хватило времени на дегустацию.",
    status: "approved",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "mock-review-3",
    activityId: "extreme-rafting",
    clientEmail: "alexey@example.com",
    clientName: "Алексей Кузнецов",
    rating: 5,
    text: "Адреналин зашкаливает! Инструкторы профессионалы, чувствовал себя в безопасности.",
    status: "approved",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "mock-review-4",
    activityId: "gastronomic-tour",
    clientEmail: "test@example.com",
    clientName: "Тест Пользователь",
    rating: 3,
    text: "Неплохо, но ожидал большего. Есть над чем поработать.",
    status: "pending",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];

export const mockSliderImages: SliderImage[] = [];

export const mockOrders: OrderRecord[] = [
  {
    id: "mock-order-1",
    orderNumber: "000001",
    bookingId: "mock-booking-1",
    clientEmail: "test@example.com",
    clientName: "Тест Пользователь",
    clientPhone: "+7 (999) 123-45-67",
    activityId: "gastronomic-tour",
    activityTitle: "Гастрономический тур",
    partnerEmail: null,
    date: new Date(Date.now() + 86400000 * 7).toISOString().split("T")[0],
    time: "12:00",
    price: 3500,
    status: "confirmed",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "mock-order-2",
    orderNumber: "000002",
    bookingId: "mock-booking-2",
    clientEmail: "test@example.com",
    clientName: "Тест Пользователь",
    clientPhone: "+7 (999) 123-45-67",
    activityId: "extreme-rafting",
    activityTitle: "Рафтинг по горной реке",
    partnerEmail: "partner@example.com",
    date: new Date(Date.now() + 86400000 * 14).toISOString().split("T")[0],
    time: null,
    price: 5000,
    status: "pending_payment",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "mock-order-3",
    orderNumber: "000003",
    bookingId: "mock-partner-booking-1",
    clientEmail: "ivan@example.com",
    clientName: "Иван Петров",
    clientPhone: "+7 (999) 111-22-33",
    activityId: "morskoe-puteshestvie",
    activityTitle: "Морское путешествие",
    partnerEmail: "partner@example.com",
    date: new Date(Date.now() + 86400000 * 5).toISOString().split("T")[0],
    time: "10:00",
    price: 5000,
    status: "confirmed",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "mock-order-4",
    orderNumber: "000004",
    bookingId: "mock-partner-booking-2",
    clientEmail: "elena@example.com",
    clientName: "Елена Смирнова",
    clientPhone: "+7 (999) 444-55-66",
    activityId: "morskoe-puteshestvie",
    activityTitle: "Морское путешествие",
    partnerEmail: "partner@example.com",
    date: new Date(Date.now() + 86400000 * 12).toISOString().split("T")[0],
    time: null,
    price: 5000,
    status: "confirmed",
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-order-5",
    orderNumber: "000005",
    bookingId: "mock-partner-booking-3",
    clientEmail: "alexey@example.com",
    clientName: "Алексей Кузнецов",
    clientPhone: "+7 (999) 777-88-99",
    activityId: "gornyj-trekking-aj-petri",
    activityTitle: "Горный треккинг на Ай-Петри",
    partnerEmail: "partner@example.com",
    date: new Date(Date.now() + 86400000 * 8).toISOString().split("T")[0],
    time: "08:00",
    price: 3500,
    status: "pending_payment",
    createdAt: new Date().toISOString(),
  },
];
