import { Service } from "./models";
import type {
  NotificationRecord,
  ActivityRecord,
  SectionRecord,
  ActivityCalendarRecord,
  BookingRecord,
  EmailSettingsRecord,
  PaymentSettingsRecord,
  AdminRecord,
  ClientRecord,
  PartnerRecord,
  AgentRecord,
  PasswordResetRecord,
  MenuItemRecord,
  AnalyticsCounterRecord,
  OrderRecord,
  ReviewRecord,
  CityRecord,
  ChatMessageRecord,
  InfoPageRecord,
  AgentStatsRecord,
} from "./models";
import type { SliderImage, OrderSettingsRecord } from "./models";

export const mockServices: Service[] = [
  {
    id: "mock-service-1",
    name: "API Gateway",
    description: "Шлюз для микросервисной архитектуры",
    status: "active",
    url: "https://api.example.com",
    createdAt: new Date("2024-01-15").toISOString(),
    updatedAt: new Date("2024-01-15").toISOString(),
  },
  {
    id: "mock-service-2",
    name: "Auth Service",
    description: "Сервис аутентификации и авторизации",
    status: "active",
    url: "https://auth.example.com",
    createdAt: new Date("2024-02-01").toISOString(),
    updatedAt: new Date("2024-02-01").toISOString(),
  },
  {
    id: "mock-service-3",
    name: "ML Pipeline",
    description: "Пайплайн для обработки данных с AI",
    status: "deploying",
    url: undefined,
    createdAt: new Date("2024-03-10").toISOString(),
    updatedAt: new Date("2024-03-10").toISOString(),
  },
];

export const mockActivities: ActivityRecord[] = [];

export const mockSections: SectionRecord[] = [];

export const mockCalendars: ActivityCalendarRecord[] = [];

export const mockBookings: BookingRecord[] = [
  {
    id: "mock-booking-1",
    clientEmail: "test@example.com",
    clientName: "Тест Пользователь",
    clientPhone: "+7 (999) 123-45-67",
    activityId: "gastronomic-tour",
    activityTitle: "Гастрономический тур",
    date: new Date(Date.now() + 86400000 * 7).toISOString().split("T")[0],
    time: "12:00",
    details: "",
    price: 3500,
    status: "confirmed",
    paymentId: null,
    paymentUrl: null,
    paymentStatus: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-booking-2",
    clientEmail: "test@example.com",
    clientName: "Тест Пользователь",
    clientPhone: "+7 (999) 123-45-67",
    activityId: "extreme-rafting",
    activityTitle: "Рафтинг по горной реке",
    date: new Date(Date.now() + 86400000 * 14).toISOString().split("T")[0],
    time: null,
    details: "Хочу увидеть пороги!",
    price: 5000,
    status: "pending_payment",
    paymentId: "mock-payment-id",
    paymentUrl: null,
    paymentStatus: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-booking-3",
    clientEmail: "test@example.com",
    clientName: "Тест Пользователь",
    clientPhone: "+7 (999) 123-45-67",
    activityId: "extreme-rafting",
    activityTitle: "Рафтинг по горной реке",
    date: new Date(Date.now() - 86400000 * 30).toISOString().split("T")[0],
    time: "14:00",
    details: "Отменили по погодным условиям",
    price: 5000,
    status: "cancelled",
    paymentId: null,
    paymentUrl: null,
    paymentStatus: null,
    createdAt: new Date(Date.now() - 86400000 * 35).toISOString(),
  },
];

export const mockEmailSettings: EmailSettingsRecord = {
  id: "default",
  emails: ["artkmv1@ya.ru"],
  defaultEmail: "artkmv1@ya.ru",
  updatedAt: new Date().toISOString(),
};

export const mockPaymentSettings: PaymentSettingsRecord = {
  id: "default",
  terminalKey: "",
  password: "",
  webhookUrl: "",
  updatedAt: new Date().toISOString(),
};

export const mockAdmins: AdminRecord[] = [
  {
    email: "artkmv1@ya.ru",
    password: "Artkmv11",
    name: "Главный администратор",
    role: "main_admin",
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
];

export const mockClients: ClientRecord[] = [
  {
    email: "ivan@example.com",
    name: "Иван Петров",
    phone: "+7 (999) 111-22-33",
    passwordHash: "hash123",
    createdAt: new Date("2024-03-01").toISOString(),
  },
  {
    email: "elena@example.com",
    name: "Елена Смирнова",
    phone: "+7 (999) 444-55-66",
    passwordHash: "hash456",
    createdAt: new Date("2024-04-15").toISOString(),
  },
  {
    email: "alexey@example.com",
    name: "Алексей Кузнецов",
    phone: "+7 (999) 777-88-99",
    passwordHash: "hash789",
    createdAt: new Date("2024-05-20").toISOString(),
  },
];

export const mockPartners: PartnerRecord[] = [
  {
    email: "partner@example.com",
    name: "Партнёр Иванов",
    phone: "+7 (999) 000-11-22",
    passwordHash: "hash:partner",
    photo: "",
    slug: "partner-ivanov",
    description:
      "<p>Профессиональный организатор активного отдыха в Крыму. Более 5 лет опыта проведения морских прогулок, треккинга и экскурсий.</p>",
    orderFormEnabled: true,
    blocked: false,
    documentNumber: "26-С-123456-26",
    legalData: {
      country: "Россия",
      status: "ip",
      fullName: "Иванов Иван Иванович",
      document: "passport_rf",
      documentSeriesNumber: "4510 123456",
      issueDate: "2015-06-15",
      tin: "770012345678",
    },
    createdAt: new Date("2024-06-01").toISOString(),
  },
];

export const mockAgents: AgentRecord[] = [
  {
    email: "agent@example.com",
    name: "Агент Смирнова",
    phone: "+7 (999) 333-22-11",
    passwordHash: "hash:agent",
    code: "AGT-DEMO-001",
    blocked: false,
    createdAt: new Date("2024-08-01").toISOString(),
  },
];

export const mockPartnerActivities: ActivityRecord[] = [
  {
    id: "morskoe-puteshestvie",
    title: "Морское путешествие",
    shortDescription: "Увлекательная прогулка на яхте вдоль побережья",
    description: "<p>Приглашаем вас в незабываемое морское путешествие!</p>",
    images: [],
    section: "vodnye",
    price: 5000,
    likes: 0,
    isPopular: false,
    over18: false,
    orderType: "order_form",
    activityType: "individual",
    imageGradient: "from-blue-400 to-cyan-500",
    location: "г. Севастополь",
    status: "active",
    partnerEmail: "partner@example.com",
    createdAt: new Date("2024-07-01").toISOString(),
    updatedAt: new Date("2024-07-03").toISOString(),
  },
  {
    id: "gornyj-trekking-aj-petri",
    title: "Горный треккинг на Ай-Петри",
    shortDescription: "Восхождение на одну из красивейших гор Крыма",
    description: "<p>Покорите вершину Ай-Петри!</p>",
    images: [],
    section: "trekking",
    price: 3500,
    likes: 0,
    isPopular: false,
    over18: false,
    orderType: "order_form",
    activityType: "individual",
    imageGradient: "from-emerald-400 to-cyan-500",
    location: "г. Ялта",
    status: "active",
    partnerEmail: "partner@example.com",
    createdAt: new Date("2024-07-02").toISOString(),
    updatedAt: new Date("2024-07-04").toISOString(),
  },
  {
    id: "degustacia-vin",
    title: "Дегустация крымских вин",
    shortDescription: "Знакомство с лучшими винодельнями полуострова",
    description: "<p>Откройте для себя мир крымского виноделия!</p>",
    images: [],
    section: "gastronomiya",
    price: 2500,
    likes: 2,
    isPopular: false,
    over18: true,
    orderType: "order_form",
    activityType: "individual",
    imageGradient: "from-rose-400 to-purple-500",
    location: "г. Балаклава",
    status: "pending",
    partnerEmail: "partner@example.com",
    createdAt: new Date("2024-08-01").toISOString(),
    updatedAt: new Date("2024-08-01").toISOString(),
  },
  {
    id: "kvest-po-staromu-gorodu",
    title: "Квест по старому городу",
    shortDescription: "Интерактивная прогулка с загадками и историей",
    description: "<p>Узнайте город с новой стороны!</p>",
    images: [],
    section: "razvlecheniya",
    price: 1500,
    likes: 0,
    isPopular: false,
    over18: false,
    orderType: "order_form",
    activityType: "individual",
    imageGradient: "from-amber-400 to-orange-500",
    location: "г. Симферополь",
    status: "rejected",
    partnerEmail: "partner@example.com",
    createdAt: new Date("2024-07-15").toISOString(),
    updatedAt: new Date("2024-07-20").toISOString(),
  },
];

export const mockPartnerBookings: BookingRecord[] = [
  {
    id: "mock-partner-booking-1",
    clientEmail: "ivan@example.com",
    clientName: "Иван Петров",
    clientPhone: "+7 (999) 111-22-33",
    activityId: "morskoe-puteshestvie",
    activityTitle: "Морское путешествие",
    date: new Date(Date.now() + 86400000 * 5).toISOString().split("T")[0],
    time: "10:00",
    details: "Жду с нетерпением!",
    price: 5000,
    status: "confirmed",
    paymentId: null,
    paymentUrl: null,
    paymentStatus: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-partner-booking-2",
    clientEmail: "elena@example.com",
    clientName: "Елена Смирнова",
    clientPhone: "+7 (999) 444-55-66",
    activityId: "morskoe-puteshestvie",
    activityTitle: "Морское путешествие",
    date: new Date(Date.now() + 86400000 * 12).toISOString().split("T")[0],
    time: null,
    details: "Хочу взять с собой ребёнка, возможно ли это?",
    price: 5000,
    status: "confirmed",
    paymentId: null,
    paymentUrl: null,
    paymentStatus: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-partner-booking-3",
    clientEmail: "alexey@example.com",
    clientName: "Алексей Кузнецов",
    clientPhone: "+7 (999) 777-88-99",
    activityId: "gornyj-trekking-aj-petri",
    activityTitle: "Горный треккинг на Ай-Петри",
    date: new Date(Date.now() + 86400000 * 8).toISOString().split("T")[0],
    time: "08:00",
    details: "",
    price: 3500,
    status: "pending_payment",
    paymentId: "mock-payment-3",
    paymentUrl: null,
    paymentStatus: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-partner-booking-4",
    clientEmail: "ivan@example.com",
    clientName: "Иван Петров",
    clientPhone: "+7 (999) 111-22-33",
    activityId: "gornyj-trekking-aj-petri",
    activityTitle: "Горный треккинг на Ай-Петри",
    date: new Date(Date.now() + 86400000 * 3).toISOString().split("T")[0],
    time: null,
    details: "Возьму с собой снаряжение",
    price: 3500,
    status: "confirmed",
    paymentId: null,
    paymentUrl: null,
    paymentStatus: null,
    createdAt: new Date().toISOString(),
  },
];

export const mockPendingActivities: ActivityRecord[] = [
  {
    id: "degustacia-vin",
    title: "Дегустация крымских вин",
    shortDescription: "Знакомство с лучшими винодельнями полуострова",
    description: "<p>Откройте для себя мир крымского виноделия!</p>",
    images: [],
    section: "gastronomiya",
    price: 2500,
    likes: 2,
    isPopular: false,
    over18: true,
    orderType: "order_form",
    activityType: "individual",
    imageGradient: "from-rose-400 to-purple-500",
    location: "г. Балаклава",
    status: "pending",
    partnerEmail: "partner@example.com",
    createdAt: new Date("2024-08-01").toISOString(),
    updatedAt: new Date("2024-08-01").toISOString(),
  },
];

export const mockPasswordResets: PasswordResetRecord[] = [];

export const mockMenuItems: MenuItemRecord[] = [
  {
    id: "mock-admin-dashboard",
    menuType: "admin",
    name: "Дашборд",
    url: "/admin",
    order: 1,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-admin-activities",
    menuType: "admin",
    name: "Активности",
    url: "/admin",
    order: 2,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-client-home",
    menuType: "client",
    name: "Главная",
    url: "/",
    order: 1,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-client-bookings",
    menuType: "client",
    name: "Мои бронирования",
    url: "/client/bookings",
    order: 2,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-client-notifications",
    menuType: "client",
    name: "Уведомления и чат",
    url: "/client/notifications",
    order: 3,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-partner-dashboard",
    menuType: "partner",
    name: "Дашборд",
    url: "/partner",
    order: 1,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-partner-activities",
    menuType: "partner",
    name: "Мои активности",
    url: "/partner/activities",
    order: 2,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-partner-orders",
    menuType: "partner",
    name: "Заказы",
    url: "/partner/orders",
    order: 3,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-partner-profile",
    menuType: "partner",
    name: "Профиль",
    url: "/partner/profile",
    order: 4,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-partner-public-profile",
    menuType: "partner",
    name: "Публичный профиль",
    url: "/partner/profile/public",
    order: 5,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-partner-notifications",
    menuType: "partner",
    name: "Уведомления и чат",
    url: "/partner/notifications",
    order: 6,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-footer-about",
    menuType: "footer",
    name: "О нас",
    url: "/about",
    order: 1,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-footer-contacts",
    menuType: "footer",
    name: "Контакты",
    url: "/contacts",
    order: 2,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "mock-footer-policy",
    menuType: "footer",
    name: "Политика конфиденциальности",
    url: "/privacy",
    order: 3,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
];

export const mockAnalyticsCounters: AnalyticsCounterRecord[] = [];

export const mockNotifications: NotificationRecord[] = [
  {
    id: "mock-notif-client-1",
    recipientEmail: "test@example.com",
    type: "booking_status",
    title: "Бронирование подтверждено",
    message:
      "Ваше бронирование на «Гастрономический тур» подтверждено. Дата: 12 августа 2025.",
    link: "/client/bookings/mock-booking-1",
    isRead: false,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "mock-notif-client-2",
    recipientEmail: "test@example.com",
    type: "booking_status",
    title: "Ожидает оплаты",
    message:
      "Бронирование на «Рафтинг по горной реке» ожидает оплаты. Перейдите к оплате, чтобы завершить бронирование.",
    link: "/client/bookings/mock-booking-2",
    isRead: false,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "mock-notif-client-3",
    recipientEmail: "test@example.com",
    type: "booking_status",
    title: "Бронирование отменено",
    message:
      "Бронирование на «Рафтинг по горной реке» отменено по погодным условиям.",
    link: "/client/bookings/mock-booking-3",
    isRead: true,
    createdAt: new Date(Date.now() - 86400000 * 35).toISOString(),
  },
  {
    id: "mock-notif-partner-1",
    recipientEmail: "partner@example.com",
    type: "new_order",
    title: "Новый заказ",
    message: "Иван Петров забронировал «Морское путешествие» на 26 июля 2025.",
    link: "/partner/orders",
    isRead: false,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "mock-notif-partner-2",
    recipientEmail: "partner@example.com",
    type: "new_order",
    title: "Новый заказ",
    message:
      "Елена Смирнова забронировала «Морское путешествие» на 2 августа 2025.",
    link: "/partner/orders",
    isRead: false,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "mock-notif-partner-3",
    recipientEmail: "partner@example.com",
    type: "activity_status",
    title: "Активность отклонена",
    message: "Ваша активность «Квест по старому городу» отклонена модератором.",
    link: "/partner/activities",
    isRead: true,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "mock-notif-partner-4",
    recipientEmail: "partner@example.com",
    type: "activity_status",
    title: "Активность на проверке",
    message:
      "Ваша активность «Дегустация крымских вин» отправлена на проверку модератору.",
    link: "/partner/activities",
    isRead: false,
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
];

export const mockChatMessages: ChatMessageRecord[] = [
  {
    id: "mock-chat-1",
    orderId: "mock-order-3",
    senderEmail: "ivan@example.com",
    senderRole: "client",
    text: "Здравствуйте! Хотел уточнить, где именно происходит сбор перед морской прогулкой?",
    clientEmail: "ivan@example.com",
    partnerEmail: "partner@example.com",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "mock-chat-2",
    orderId: "mock-order-3",
    senderEmail: "partner@example.com",
    senderRole: "partner",
    text: "Здравствуйте! Сбор на причале №5 в Севастополе, бухта Артиллерийская. За 15 минут до начала.",
    clientEmail: "ivan@example.com",
    partnerEmail: "partner@example.com",
    createdAt: new Date(Date.now() - 86400000 * 2 + 3600000).toISOString(),
  },
  {
    id: "mock-chat-3",
    orderId: "mock-order-3",
    senderEmail: "ivan@example.com",
    senderRole: "client",
    text: "Спасибо! А что нужно брать с собой?",
    clientEmail: "ivan@example.com",
    partnerEmail: "partner@example.com",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "mock-chat-4",
    orderId: "mock-order-3",
    senderEmail: "partner@example.com",
    senderRole: "partner",
    text: "Возьмите головной убор, крем от загара и воду. Остальное предоставим мы.",
    clientEmail: "ivan@example.com",
    partnerEmail: "partner@example.com",
    createdAt: new Date(Date.now() - 86400000 + 1800000).toISOString(),
  },
  {
    id: "mock-chat-5",
    orderId: "mock-order-4",
    senderEmail: "elena@example.com",
    senderRole: "client",
    text: "Добрый день! Можно ли перенести прогулку на день раньше?",
    clientEmail: "elena@example.com",
    partnerEmail: "partner@example.com",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const mockReviews: ReviewRecord[] = [
  {
    id: "mock-review-1",
    activityId: "gastronomic-tour",
    clientEmail: "ivan@example.com",
    clientName: "Иван Петров",
    rating: 5,
    text: "Отличный тур! Всё очень понравилось, особенно дегустация местных вин. Обязательно вернусь ещё.",
    status: "approved",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "mock-review-2",
    activityId: "gastronomic-tour",
    clientEmail: "elena@example.com",
    clientName: "Елена Смирнова",
    rating: 4,
    text: "Хорошая организация, вкусная еда. Немного не хватило времени на дегустацию.",
    status: "approved",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "mock-review-3",
    activityId: "extreme-rafting",
    clientEmail: "alexey@example.com",
    clientName: "Алексей Кузнецов",
    rating: 5,
    text: "Адреналин зашкаливает! Инструкторы профессионалы, чувствовал себя в безопасности.",
    status: "approved",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "mock-review-4",
    activityId: "gastronomic-tour",
    clientEmail: "test@example.com",
    clientName: "Тест Пользователь",
    rating: 3,
    text: "Неплохо, но ожидал большего. Есть над чем поработать.",
    status: "pending",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];

export const mockOrderSettings: OrderSettingsRecord = {
  id: "default",
  orderFormEnabled: true,
  updatedAt: new Date().toISOString(),
};

export const mockSliderImages: SliderImage[] = [];

export const mockCities: CityRecord[] = [
  { name: "Севастополь", createdAt: new Date("2024-01-01").toISOString() },
  { name: "Симферополь", createdAt: new Date("2024-01-01").toISOString() },
  { name: "Ялта", createdAt: new Date("2024-01-01").toISOString() },
  { name: "Москва", createdAt: new Date("2024-01-01").toISOString() },
  { name: "Санкт-Петербург", createdAt: new Date("2024-01-01").toISOString() },
];

export const mockInfoPages: InfoPageRecord[] = [
  {
    id: "info-partner-1",
    target: "partner",
    title: "Как добавлять активности",
    content:
      "<p>Для добавления новой активности перейдите в раздел <strong>«Добавить активность»</strong> в боковом меню. Заполните название, описание, загрузите фотографии и укажите цену. После отправки активность будет проверена модератором.</p>",
    createdAt: new Date("2025-01-01").toISOString(),
    updatedAt: new Date("2025-01-01").toISOString(),
  },
  {
    id: "info-partner-2",
    target: "partner",
    title: "Правила размещения",
    content:
      "<p>Все активности проходят модерацию перед публикацией. Запрещено размещать активности, противоречащие законодательству РФ. Фотографии должны быть хорошего качества и соответствовать содержанию активности.</p>",
    createdAt: new Date("2025-01-02").toISOString(),
    updatedAt: new Date("2025-01-02").toISOString(),
  },
  {
    id: "info-partner-3",
    target: "partner",
    title: "Комиссия и выплаты",
    content:
      "<p>Комиссия платформы составляет <strong>10%</strong> от стоимости каждой проданной активности. Выплаты производятся ежемесячно при сумме от 1000₽. Подробнее в разделе «Финансы».</p>",
    createdAt: new Date("2025-01-03").toISOString(),
    updatedAt: new Date("2025-01-03").toISOString(),
  },
  {
    id: "info-tourist-1",
    target: "tourist",
    title: "Как забронировать активность",
    content:
      "<p>Чтобы забронировать активность, выберите понравившийся тур или мероприятие на главной странице, нажмите «Забронировать» и следуйте инструкциям. После подтверждения бронирования вы получите уведомление.</p>",
    createdAt: new Date("2025-02-01").toISOString(),
    updatedAt: new Date("2025-02-01").toISOString(),
  },
  {
    id: "info-tourist-2",
    target: "tourist",
    title: "Правила отмены бронирования",
    content:
      "<p>Отмена бронирования возможна не позднее чем за <strong>24 часа</strong> до начала активности. При отмене позднее этого срока стоимость может быть удержана полностью. Для отмены перейдите в раздел «Мои бронирования».</p>",
    createdAt: new Date("2025-02-02").toISOString(),
    updatedAt: new Date("2025-02-02").toISOString(),
  },
  {
    id: "info-tourist-3",
    target: "tourist",
    title: "Способы оплаты",
    content:
      "<p>Мы принимаем оплату банковскими картами <strong>Visa, Mastercard, МИР</strong>, а также через СБП (Система быстрых платежей). Все платежи защищены и проходят через безопасный шлюз.</p>",
    createdAt: new Date("2025-02-03").toISOString(),
    updatedAt: new Date("2025-02-03").toISOString(),
  },
  {
    id: "info-tourist-4",
    target: "tourist",
    title: "Что взять с собой на активность",
    content:
      "<p>Рекомендуем взять с собой удобную одежду по погоде, бутылку воды, головной убор в солнечную погоду. Для некоторых активностей может потребоваться специальное снаряжение — уточняйте у организатора.</p>",
    createdAt: new Date("2025-02-04").toISOString(),
    updatedAt: new Date("2025-02-04").toISOString(),
  },
  {
    id: "info-tourist-5",
    target: "tourist",
    title: "Безопасность на мероприятиях",
    content:
      "<p>Все организаторы проходят проверку перед размещением. Активности маркируются по уровню сложности. Если активность помечена <strong>18+</strong>, участвовать могут только совершеннолетние.</p>",
    createdAt: new Date("2025-02-05").toISOString(),
    updatedAt: new Date("2025-02-05").toISOString(),
  },
  {
    id: "info-tourist-6",
    target: "tourist",
    title: "Как оставить отзыв",
    content:
      "<p>После завершения активности вы можете оставить отзыв в разделе «Мои бронирования». Оценки и отзывы помогают другим туристам выбрать лучшее мероприятие.</p>",
    createdAt: new Date("2025-02-06").toISOString(),
    updatedAt: new Date("2025-02-06").toISOString(),
  },
  {
    id: "info-tourist-7",
    target: "tourist",
    title: "Связь с организатором",
    content:
      "<p>Если у вас возникли вопросы до или во время активности, вы можете связаться с организатором через чат в разделе «Уведомления и чат». Организатор ответит в рабочее время.</p>",
    createdAt: new Date("2025-02-07").toISOString(),
    updatedAt: new Date("2025-02-07").toISOString(),
  },
  {
    id: "info-tourist-8",
    target: "tourist",
    title: "Программа лояльности",
    content:
      "<p>За каждую оплаченную активность вы получаете <strong>бонусные баллы</strong>. Баллы можно использовать для частичной оплаты следующих бронирований. Подробнее в личном кабинете.</p>",
    createdAt: new Date("2025-02-08").toISOString(),
    updatedAt: new Date("2025-02-08").toISOString(),
  },
  {
    id: "info-tourist-9",
    target: "tourist",
    title: "Групповые и индивидуальные активности",
    content:
      "<p>Активности бывают <strong>групповые</strong> (вы присоединяетесь к группе) и <strong>индивидуальные</strong> (только вы и ваша компания). Выбирайте подходящий формат на странице мероприятия.</p>",
    createdAt: new Date("2025-02-09").toISOString(),
    updatedAt: new Date("2025-02-09").toISOString(),
  },
  {
    id: "info-tourist-10",
    target: "tourist",
    title: "Погода и перенос активности",
    content:
      "<p>При неблагоприятных погодных условиях организатор может перенести или отменить активность. В этом случае вам будет предложена альтернативная дата или полный возврат средств.</p>",
    createdAt: new Date("2025-02-10").toISOString(),
    updatedAt: new Date("2025-02-10").toISOString(),
  },
  {
    id: "info-tourist-11",
    target: "tourist",
    title: "Как добраться до места",
    content:
      "<p>Подробные инструкции по проезду и точное место сбора отображаются в карточке активности после бронирования. При необходимости воспользуйтесь картами или такси.</p>",
    createdAt: new Date("2025-02-11").toISOString(),
    updatedAt: new Date("2025-02-11").toISOString(),
  },
  {
    id: "info-tourist-12",
    target: "tourist",
    title: "Фото и видео на мероприятиях",
    content:
      "<p>Вы можете делать фото и видео во время активности, если это не оговорено отдельно. Делитесь впечатлениями в соцсетях и отмечайте организатора!</p>",
    createdAt: new Date("2025-02-12").toISOString(),
    updatedAt: new Date("2025-02-12").toISOString(),
  },
  {
    id: "info-agent-1",
    target: "agent",
    title: "Как привлекать партнёров",
    content:
      "<p>Делитесь вашей партнёрской ссылкой в соцсетях и мессенджерах. Каждый партнёр, зарегистрировавшийся по вашей ссылке, автоматически привязывается к вам. Чем больше партнёров вы привлечёте — тем выше ваш заработок.</p>",
    createdAt: new Date("2025-03-01").toISOString(),
    updatedAt: new Date("2025-03-01").toISOString(),
  },
  {
    id: "info-agent-2",
    target: "agent",
    title: "Как рассчитывается ваш процент",
    content:
      "<p>Вы получаете процент с каждой успешной оплаты активности ваших партнёров. Ставка зависит от объёма продаж за месяц и растёт по лесенке <strong>3% → 4% → 5%</strong>. Пороги задаёт администратор.</p>",
    createdAt: new Date("2025-03-02").toISOString(),
    updatedAt: new Date("2025-03-02").toISOString(),
  },
  {
    id: "info-agent-3",
    target: "agent",
    title: "Вывод заработка",
    content:
      "<p>Вы можете вывести заработок раз в месяц. Для этого подайте заявку в разделе «Заработок и выплаты». После подтверждения администратором вы увидите пометку «ожидайте выплату».</p>",
    createdAt: new Date("2025-03-03").toISOString(),
    updatedAt: new Date("2025-03-03").toISOString(),
  },
];

export const mockOrders: OrderRecord[] = [
  {
    id: "mock-order-1",
    orderNumber: "000001",
    bookingId: "mock-booking-1",
    clientEmail: "test@example.com",
    clientName: "Тест Пользователь",
    clientPhone: "+7 (999) 123-45-67",
    activityId: "gastronomic-tour",
    activityTitle: "Гастрономический тур",
    partnerEmail: null,
    date: new Date(Date.now() + 86400000 * 7).toISOString().split("T")[0],
    time: "12:00",
    price: 3500,
    status: "paid",
    wasPaid: true,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "mock-order-2",
    orderNumber: "000002",
    bookingId: "mock-booking-2",
    clientEmail: "test@example.com",
    clientName: "Тест Пользователь",
    clientPhone: "+7 (999) 123-45-67",
    activityId: "extreme-rafting",
    activityTitle: "Рафтинг по горной реке",
    partnerEmail: "partner@example.com",
    date: new Date(Date.now() + 86400000 * 14).toISOString().split("T")[0],
    time: null,
    price: 5000,
    status: "pending_payment",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "mock-order-3",
    orderNumber: "000003",
    bookingId: "mock-partner-booking-1",
    clientEmail: "ivan@example.com",
    clientName: "Иван Петров",
    clientPhone: "+7 (999) 111-22-33",
    activityId: "morskoe-puteshestvie",
    activityTitle: "Морское путешествие",
    partnerEmail: "partner@example.com",
    date: new Date(Date.now() + 86400000 * 5).toISOString().split("T")[0],
    time: "10:00",
    price: 5000,
    status: "paid",
    wasPaid: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "mock-order-4",
    orderNumber: "000004",
    bookingId: "mock-partner-booking-2",
    clientEmail: "elena@example.com",
    clientName: "Елена Смирнова",
    clientPhone: "+7 (999) 444-55-66",
    activityId: "morskoe-puteshestvie",
    activityTitle: "Морское путешествие",
    partnerEmail: "partner@example.com",
    date: new Date(Date.now() + 86400000 * 12).toISOString().split("T")[0],
    time: null,
    price: 5000,
    status: "cancelled",
    wasPaid: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-order-5",
    orderNumber: "000005",
    bookingId: "mock-partner-booking-3",
    clientEmail: "alexey@example.com",
    clientName: "Алексей Кузнецов",
    clientPhone: "+7 (999) 777-88-99",
    activityId: "gornyj-trekking-aj-petri",
    activityTitle: "Горный треккинг на Ай-Петри",
    partnerEmail: "partner@example.com",
    date: new Date(Date.now() + 86400000 * 8).toISOString().split("T")[0],
    time: "08:00",
    price: 3500,
    status: "pending_payment",
    createdAt: new Date().toISOString(),
  },
];

export const mockAgentStats: AgentStatsRecord[] = [
  {
    agentEmail: "agent@example.com",
    clicks30: 48,
    registrations30: 5,
    updatedAt: new Date().toISOString(),
  },
];
